config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :welcome
  resources :users do 
    resources :avatars, only: [:create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

  has_one_attached :avatar
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable


after_create :welcome_send

def welcome_send
  UserMailer.user_created(self).deliver_now
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session # avoid CSRF authenticity_token on android 

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
 
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up)  {|u| u.permit(:first_name, :name, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:sign_in)  {|u| u.permit(:email, :password)}
        devise_parameter_sanitizer.permit(:account_update)  {|u| u.permit(:first_name, :name, :email, :password, :password_confirmation)}
    end
    
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @user.avatar.attach(params[:avatar])
        redirect_to(user_path(@user))
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end



  def update
    @user = User.update(user_params)
  end

  def destroy
    @user = User.find(params[:id])
    @user = User.destroy
    redirect_to '/'
  end


  def edit
  end


  def create
     
    @user = User.new(user_params)
    if @user.save
      # Deliver the signup email
      UserMailer.user_created(@user).deliver_now
      mailer.confirmation_instrucions(@user).deliver_now
      redirect_to(@user, :notice => 'User created')
    else
      render :action => 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :name, :email, :login)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesignApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="usershow" style="text-align: center">

<div class="trick"></div>

 <%if @user.avatar.attached?%>
    <%= link_to  image_tag(@user.avatar, alt: 'avatar', class:'img-fluid rounded-pill', style:'height:18rem ; width:18rem'), @user.avatar %>
    <%else%>
      <p>=== Il n'y a pas de photo sur votre profil ===</p>
      <p>=== ajour votre photo ici 👇🏽 ===</p>
    <% end %>

<%= form_with(url: user_avatars_path(@user), local: true, multipart: true) do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit "Uploader l'avatar" %>
<% end %>


<h5>Votre prénom:</h5>
<%= @user.first_name %><br><br>
<h5>Votre nom:</h5>
<%= @user.name %><br><br>
<h5>Votre email:</h5>
<%= @user.email %>

<div class="trick"></div>





</div>

app/views/welcome/edit.html.erb
<h1>Welcome#edit</h1>
<p>Find me in app/views/welcome/edit.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<div class="trick"></div>




<a href="<%= new_user_session_path %>">se connecter</a><br>

<a href="<%= new_user_registration_path %>">Créer un compte</a><br><br>

<%= button_to "Se déconnecter", destroy_user_session_path, method: :delete %><br><br>


<% if user_signed_in? %>
<%= link_to "Voir mon profil", user_path(current_user.id) %>
<% else %>

<% end %>

app/views/welcome/new.html.erb
<h1>Welcome#new</h1>
<p>Find me in app/views/welcome/new.html.erb</p>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>